Algoritmo "contaraté10"
//
//
// Descrição   : conta até aonde o usuário quiser
// Autor(a)    : Júlio César Sinatora
// Data atual  : 06/09/2022
Var
   valor, contador: inteiro

Inicio
   contador <- 0
   escreva("Quer contar até quanto? ")
   leia(valor)
   enquanto (contador <= valor)faca
      escreval(contador)
      contador <- contador +1
   fimenquanto
   escreval ("Terminei de contar")
fimalgoritmo

