Algoritmo "IdadeParaentrar"

Var
   nome: caractere
   idade: inteiro

Inicio
   escreva("Qual seu nome: ")
   Leia (nome)
   escreval ("Bem vindo ",nome)
   escreval("Qual sua idade: ")
   Leia (idade)
   se (idade >=18)  então
      escreval("Parabéns você é maior de idade e pode entrar! ")
   senão
      escreva ("Que pena você é de menor, volte quando for maior. ")
   fimse

Fimalgoritmo