Algoritmo "Creuza01"
// 
//  
// Descrição   : ano atual menos ano de nascimento
// Autor(a)    : Júlio Sinatora
// Data atual  : 14/07/2022
Var

   ano_atual, ano_nasci, idade: inteiro

Inicio
      Escreva("Em que anos nós estamos ? ")
      Leia(ano_atual)
      Escreva("Que ano eu nasci? ")
      Leia(ano_nasci)
      idade <- ano_atual - ano_nasci
      Escreva("Minha idade sera ", idade)
      
      
      

Fimalgoritmo