Algoritmo "soma02"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/07/2022
Var
   n1, n2: inteiro
   s: real


Inicio
      escreva("diga um numero: ")
      leia(n1)
      escreva("diga outro numero para somar ao primeiro: ")
      leia(n2)
      s <- (n1 + n2)
      escreva("a soma do primeiro e segundo numero, é igual á ",s )


      

Fimalgoritmo